declare module "@prisma/client" {
  // Minimal types to satisfy TypeScript during CI; the real types are generated by Prisma.
  export type Decimal = any;
  export type BribeReport = {
    id: string;
    departmentCategory: string;
    serviceType: string;
    stateRegion: string;
    districtLocation: string;
    amountDemanded: Decimal | number;
    outcome: string;
    narrativeText: string;
    verificationStatus?: string;
    createdAt: string | Date;
  };
  export class PrismaClient {
    bribeReport: {
      create: (...args: any[]) => Promise<any>;
      findMany: (...args: any[]) => Promise<any[]>;
      aggregate: (...args: any[]) => Promise<any>;
      count: (...args: any[]) => Promise<number>;
    };
    [key: string]: any;
  }
  export default {} as any;
}

declare module "prisma/config" {
  export function definePrismaConfig(config: any): any;
}
